import React, { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, BrainCircuit, Building2, ChevronRight, CircleDollarSign, Cpu, Gauge, LineChart, Radio, ShieldCheck, TrendingDown, TrendingUp, Users, Wallet, Zap, Bot, Monitor, ArrowUpRight } from 'lucide-react';
import './styles.css';

type Status='ANALYZING'|'DECIDING'|'TRADING'|'RISK CHECK'|'EXECUTING'|'LEARNING';
type Page='floor'|'command'|'markets'|'agents'|'portfolio'|'risk'|'research';
type Agent={id:number;name:string;role:string;strategy:string;status:Status;action:string;symbol:string;pnl:number;skill:number;risk:number;trades:number;wins:number;position:number;seat:number};
type Market={symbol:string;price:number;change:number;history:number[]};

const names=[['ARIA','CEO / ORCHESTRATOR','Capital Allocation'],['NOVA','QUANT RESEARCH','Statistical Momentum'],['ATLAS','SENIOR TRADER','Trend Following'],['VEGA','MACRO INTELLIGENCE','Macro + News'],['SENTINEL','RISK MANAGER','Dynamic Risk'],['ORBIT','EXECUTION','Smart Execution'],['LYRA','OPTIONS QUANT','Volatility'],['HELIOS','MARKET SCOUT','Breakout Detection'],['MERCURY','FLOW ANALYST','Order Flow'],['ECHO','NEWS INTELLIGENCE','Event Driven'],['KAIROS','PORTFOLIO MANAGER','Multi-Asset'],['VECTOR','SYSTEMS QUANT','Mean Reversion']];
const symbols=['NVDA','MSFT','AAPL','BTC','SPX'];
const initialMarkets:Market[]=[
 {symbol:'NVDA',price:142.31,change:1.82,history:[136,137,138,137,139,141,140,142,141,143,142,142]},
 {symbol:'MSFT',price:505.74,change:.64,history:[499,501,500,502,504,503,505,504,506,505,505,506]},
 {symbol:'AAPL',price:245.18,change:-.38,history:[249,248,247,248,246,247,245,246,244,245,246,245]},
 {symbol:'BTC',price:113420,change:2.41,history:[109,110,111,110,112,111,113,112,114,113,114,113]},
 {symbol:'SPX',price:6512.8,change:.27,history:[6460,6480,6470,6490,6500,6490,6510,6500,6520,6510,6515,6513]}
];

function seedAgents():Agent[]{return names.map((x,i)=>({id:i+1,name:x[0],role:x[1],strategy:x[2],status:(['DECIDING','ANALYZING','TRADING','ANALYZING','RISK CHECK','EXECUTING','ANALYZING','TRADING','ANALYZING','LEARNING','DECIDING','ANALYZING'] as Status[])[i],action:['Allocating capital across desks','Scanning momentum anomalies','Managing NVDA trend position','Reading macro regime','Validating exposure limits','Routing simulated order','Pricing volatility surface','Scanning breakout candidates','Tracking institutional flow','Parsing market catalysts','Rebalancing portfolio','Testing mean-reversion signal'][i],symbol:symbols[i%symbols.length],pnl:[12840,9340,14620,-3820,5120,7880,6210,11480,4930,2780,9020,7350][i],skill:83+i%14,risk:.8+(i%8)*.35,trades:12+i*4,wins:8+i*2,position:i===2?120:i===7?80:0,seat:i}));}
const money=(n:number)=>`€${Math.round(n).toLocaleString('en-US')}`;
const short=(n:number)=>n>=1000000?`€${(n/1000000).toFixed(2)}M`:money(n);

function App(){
 const [page,setPage]=useState<Page>('floor');
 const [agents,setAgents]=useState(seedAgents);
 const [markets,setMarkets]=useState(initialMarkets);
 const [selected,setSelected]=useState(3);
 const [selectedSymbol,setSelectedSymbol]=useState('NVDA');
 const [events,setEvents]=useState(['SENTINEL approved ATLAS order','ORBIT routed NVDA BUY 120','NOVA detected momentum anomaly','VEGA updated macro risk score']);
 const [ticks,setTicks]=useState(0);

 useEffect(()=>{const t=setInterval(()=>{setTicks(v=>v+1);setMarkets(ms=>ms.map(m=>{const amp=m.symbol==='BTC'?280:m.symbol==='SPX'?7:.9;const p=Math.max(.01,m.price+(Math.random()-.46)*amp);const c=Math.max(-6,Math.min(6,m.change+(Math.random()-.48)*.28));return {...m,price:p,change:c,history:[...m.history.slice(-15),m.symbol==='BTC'?p/1000:p]};}));},1200);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!ticks)return;setAgents(as=>as.map(a=>{const m=markets.find(x=>x.symbol===a.symbol)!;const signal=m.change>1.1?'BUY':m.change<-.9?'SELL':'WAIT';let status=a.status, action=a.action, position=a.position, pnl=a.pnl, trades=a.trades, wins=a.wins;
   if(a.id%3===0&&signal==='BUY'){status='TRADING';action=`Opening ${a.symbol} position`;position=Math.min(180,position+5);trades++;}
   else if(a.id%4===0&&signal==='SELL'){status='EXECUTING';action=`Reducing ${a.symbol} exposure`;position=Math.max(0,position-5);trades++;wins+=1;}
   else if(a.id%2===0){status='ANALYZING';action=signal==='BUY'?`Confirming bullish ${a.symbol} signal`:`Scanning ${a.symbol} liquidity`;}
   else {status=a.id===5?'RISK CHECK':'LEARNING';action=a.id===5?'Recalculating portfolio risk limits':`Learning from ${a.symbol} outcome`;}
   pnl+=((Math.random()-.45)*55)+(position?((m.price-(a.symbol==='BTC'?113000:140))*0.004):0);
   return {...a,status,action,position,pnl,trades,wins,risk:Math.max(.5,Math.min(5,a.risk+(signal==='BUY'?.025:-.01)))}}));
   setEvents(e=>[`${agents[Math.floor(Math.random()*agents.length)].name} ${['evaluated','updated','detected','learned from'][Math.floor(Math.random()*4)]} ${symbols[Math.floor(Math.random()*symbols.length)]}`,...e].slice(0,9));
 },[ticks]);
 const totalPnl=agents.reduce((s,a)=>s+a.pnl,0); const aum=2000000+totalPnl; const active=agents.filter(a=>['TRADING','EXECUTING'].includes(a.status)).length; const selectedAgent=agents.find(a=>a.id===selected)||agents[0];
 const nav:[Page,string][]=[['floor','Trading Floor'],['command','Command Center'],['markets','Markets'],['agents','AI Workforce'],['portfolio','Portfolio'],['risk','Risk Engine'],['research','Research Lab']];
 return <div className="app">
  <header className="topbar"><div className="brand"><div className="brandMark">D7</div><div><b>DESTINY7 CAPITAL</b><span>AUTONOMOUS AI TRADING COMPANY</span></div></div><div className="live"><i/> SYSTEM LIVE <em>AUTONOMOUS</em></div><div className="topStats"><div><small>PAPER AUM</small><b>{short(aum)}</b></div><div><small>NET P&L</small><b className={totalPnl>=0?'up':'down'}>{totalPnl>=0?'+':''}{money(totalPnl)}</b></div><div><small>ACTIVE AGENTS</small><b>{active} / {agents.length}</b></div></div></header>
  <div className="shell"><nav className="sidebar"><div className="navTitle">COMPANY OS</div>{nav.map(([id,label])=><button key={id} className={page===id?'navActive':''} onClick={()=>setPage(id)}>{navIcon(id)}<span>{label}</span><ChevronRight size={13}/></button>)}<div className="autobox"><Zap size={16}/><b>SELF-RUNNING</b><span>Observe → Decide → Risk → Execute → Learn</span></div><div className="floorMini"><div className="miniScreen">AURORA<br/><strong>MARKETS</strong></div><span>TRADING FLOOR<br/><b>12 AI DESKS</b></span></div></nav>
  <main><div className="crumb"><span>DESTINY7 CAPITAL</span><b>/</b><strong>{nav.find(n=>n[0]===page)?.[1]}</strong><em>SIMULATION · TICK {ticks}</em></div>
   {page==='floor'&&<Floor agents={agents} selected={selected} setSelected={setSelected} markets={markets} totalPnl={totalPnl} active={active}/>} 
   {page==='command'&&<Command agents={agents} markets={markets} events={events} totalPnl={totalPnl} aum={aum} setSelected={setSelected}/>} 
   {page==='markets'&&<Markets markets={markets} selected={selectedSymbol} setSelected={setSelectedSymbol} agents={agents}/>} 
   {page==='agents'&&<Agents agents={agents} selected={selected} setSelected={setSelected}/>} 
   {page==='portfolio'&&<Portfolio agents={agents} markets={markets} totalPnl={totalPnl} aum={aum}/>} 
   {page==='risk'&&<Risk agents={agents}/>} 
   {page==='research'&&<Research agents={agents} markets={markets}/>} 
  </main>
  <aside className="inspector"><div className="inspectorTop"><div><small>ACTIVE AI EMPLOYEE</small><h2>{selectedAgent.name}</h2></div><div className="avatar">{selectedAgent.name[0]}</div></div><div className="agentRole">{selectedAgent.role}<span>RUNNING</span></div><div className="metricGrid"><div><small>P&L</small><b className={selectedAgent.pnl>=0?'up':'down'}>{selectedAgent.pnl>=0?'+':''}{money(selectedAgent.pnl)}</b></div><div><small>SKILL</small><b>{selectedAgent.skill}/100</b></div><div><small>RISK</small><b>{selectedAgent.risk.toFixed(1)}%</b></div><div><small>WIN RATE</small><b>{Math.round(selectedAgent.wins/Math.max(1,selectedAgent.trades)*100)}%</b></div></div><div className="currentAction"><small>CURRENT DECISION</small><strong>{selectedAgent.action}</strong><div><Activity size={14}/> {selectedAgent.status}</div><div><Wallet size={14}/> {selectedAgent.position} {selectedAgent.symbol}</div></div><div className="memory"><small>AGENT MEMORY</small><p>Strategy: {selectedAgent.strategy}. This agent continuously updates its behavior from simulated outcomes.</p></div><div className="listTitle">AI WORKFORCE <span>{agents.length}/50</span></div><div className="agentList">{agents.map(a=><button className={a.id===selected?'agentRow selected':''} key={a.id} onClick={()=>setSelected(a.id)}><div className="miniAvatar">{a.name[0]}</div><div><b>{a.name}</b><small>{a.status} · {a.symbol}</small></div><strong className={a.pnl>=0?'up':'down'}>{a.pnl>=0?'+':''}{money(a.pnl)}</strong></button>)}</div></aside>
  </div><footer><span><Cpu size={13}/> DECISION CORE ONLINE</span><span><ShieldCheck size={13}/> RISK ENGINE ONLINE</span><span><CircleDollarSign size={13}/> PAPER CAPITAL €2.00M</span><span><Activity size={13}/> MARKET ENGINE RUNNING</span><span>v0.3 AUTONOMOUS FLOOR</span></footer>
 </div>;
}
function navIcon(id:Page){const p=15;if(id==='floor')return <Building2 size={p}/>;if(id==='command')return <Gauge size={p}/>;if(id==='markets')return <LineChart size={p}/>;if(id==='agents')return <Users size={p}/>;if(id==='portfolio')return <Wallet size={p}/>;if(id==='risk')return <ShieldCheck size={p}/>;return <BrainCircuit size={p}/>;}
function Header({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div className="viewHead"><div><small>{eyebrow}</small><h1>{title}</h1><p>{sub}</p></div><div className="liveBox"><i/> LIVE<br/><b>AUTONOMOUS</b></div></div>}
function Floor({agents,selected,setSelected,markets,totalPnl,active}:any){return <><Header eyebrow="TRADING FLOOR" title="A living company of AI agents." sub="Every desk is an autonomous worker. Decisions, risk checks, executions and learning happen continuously."/><div className="floorStats"><div><small>DESKS ONLINE</small><b>{agents.length}</b><span>AI employees</span></div><div><small>ACTIVE TRADES</small><b>{active}</b><span>positions moving</span></div><div><small>COMPANY P&L</small><b className={totalPnl>=0?'up':'down'}>{totalPnl>=0?'+':''}{money(totalPnl)}</b><span>simulated</span></div><div><small>MARKET REGIME</small><b>BULLISH</b><span>risk monitored</span></div></div><div className="floorScene"><div className="roofGlow"/><div className="frontWall"><div className="megaScreen"><div className="screenBrand">AURORA CORP</div><div className="screenTitle">GLOBAL MARKET COMMAND</div><div className="screenCharts"><div className="screenLine"/><div className="screenLine second"/><div className="screenNumbers">NVDA <b>+1.82%</b> · BTC <b>+2.41%</b> · SPX <b>+0.27%</b></div></div></div><div className="wallLabel">DESTINY7 CAPITAL · AUTONOMOUS FINANCIAL COMPANY</div></div><div className="floorPlane"><div className="centralAisle"><span>AI OPERATIONS</span></div>{agents.map((a:any,i:number)=><Desk key={a.id} agent={a} index={i} selected={selected===a.id} onClick={()=>setSelected(a.id)}/>) }<div className="cashVault"><CircleDollarSign size={18}/><b>€2.00M</b><span>PAPER CAPITAL</span></div></div><div className="sceneCaption"><span><i/> LIVE SIMULATION</span><b>Click any desk to inspect the agent</b></div></div><div className="floorBottom"><div className="card"><div className="cardHead"><span>MARKET PULSE</span><b>LIVE</b></div>{markets.map((m:any)=><div className="marketRow" key={m.symbol}><b>{m.symbol}</b><span>{m.price.toLocaleString(undefined,{maximumFractionDigits:2})}</span><strong className={m.change>=0?'up':'down'}>{m.change>=0?'+':''}{m.change.toFixed(2)}%</strong></div>)}</div><div className="card"><div className="cardHead"><span>HOW THE FLOOR WORKS</span><Bot size={16}/></div><div className="flow"><span>OBSERVE</span><b>→</b><span>DECIDE</span><b>→</b><span>RISK</span><b>→</b><span>EXECUTE</span><b>→</b><span>LEARN</span></div><p>No human button is required for the simulation to operate.</p></div></div></>}
function Desk({agent,index,selected,onClick}:any){const x=[8,27,46,65,84,17,36,55,74,27,56,78][index];const y=index<5?18:index<9?48:68;return <button className={`desk ${selected?'deskSelected':''}`} style={{left:`${x}%`,top:`${y}%`}} onClick={onClick}><div className="chair"/><div className="deskTop"><div className="monitor"><div className="monitorGlow"><span>{agent.symbol}</span><b>{agent.pnl>=0?'+':''}{Math.round(agent.pnl/100)/10}k</b></div></div><div className="keyboard"/><div className="cashStack"><i/><i/><i/></div></div><div className="agentFigure"><div className="head">{agent.name[0]}</div><div className="body"/></div><div className="deskTag"><b>{agent.name}</b><span>{agent.status}</span></div></button>}
function Command({agents,markets,events,totalPnl,aum,setSelected}:any){return <><Header eyebrow="COMMAND CENTER" title="The company runs itself." sub="The autonomous loop is always active: markets feed the agents, agents decide, risk validates, execution acts, learning updates the next decision."/><div className="process"><div><b>01</b><strong>OBSERVE</strong><span>prices · volume · news</span></div><i>→</i><div><b>02</b><strong>DECIDE</strong><span>strategy · memory · signal</span></div><i>→</i><div><b>03</b><strong>RISK</strong><span>limits · exposure · correlation</span></div><i>→</i><div><b>04</b><strong>EXECUTE</strong><span>order · position · P&L</span></div><i>→</i><div><b>05</b><strong>LEARN</strong><span>outcome · skill · memory</span></div></div><div className="commandGrid"><div className="heroCard"><small>COMPANY PERFORMANCE</small><h2>{short(aum)}</h2><span>simulated assets under management</span><strong className={totalPnl>=0?'up':'down'}>{totalPnl>=0?'+':''}{money(totalPnl)}</strong><div className="barChart">{[30,44,39,62,54,72,66,80,73,94,88,100].map((h:number,i:number)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="card"><div className="cardHead"><span>LIVE AI DECISIONS</span><b>{agents.filter((a:any)=>a.status==='TRADING'||a.status==='EXECUTING').length} ACTIVE</b></div>{agents.slice(0,7).map((a:any)=><button className="decision" key={a.id} onClick={()=>setSelected(a.id)}><i/><div><b>{a.name}</b><span>{a.action}</span></div><strong className={a.pnl>=0?'up':'down'}>{a.pnl>=0?'+':''}{money(a.pnl)}</strong></button>)}</div><div className="card"><div className="cardHead"><span>EVENT STREAM</span><Radio size={15}/></div>{events.map((e:string,i:number)=><div className="event" key={i}><i/>{e}</div>)}</div></div></>}
function Markets({markets,selected,setSelected,agents}:any){const m=markets.find((x:any)=>x.symbol===selected)!;return <><Header eyebrow="MARKETS" title="The information layer." sub="A simulated market continuously changes. Agents consume the same stream and form different decisions."/><div className="marketPage"><div className="card symbolList">{markets.map((x:any)=><button className={x.symbol===selected?'symbolActive':''} key={x.symbol} onClick={()=>setSelected(x.symbol)}><b>{x.symbol}</b><span>{x.price.toLocaleString(undefined,{maximumFractionDigits:2})}</span><strong className={x.change>=0?'up':'down'}>{x.change>=0?'+':''}{x.change.toFixed(2)}%</strong></button>)}</div><div className="card bigChart"><div className="cardHead"><span>{m.symbol} · PRICE STREAM</span><b>LIVE</b></div><div className="chartVisual">{m.history.map((v:number,i:number)=><i key={i} style={{left:`${i*6.5}%`,bottom:`${20+((v-Math.min(...m.history))/(Math.max(...m.history)-Math.min(...m.history)+.001))*60}%`}}/>)}</div><div className="owners">{agents.filter((a:any)=>a.symbol===selected).map((a:any)=><span key={a.id}>{a.name} · {a.status}</span>)}</div></div></div></>}
function Agents({agents,selected,setSelected}:any){return <><Header eyebrow="AI WORKFORCE" title="12 agents. 50 seats ready." sub="Each employee has a role, strategy, memory, risk profile and evolving skill score."/><div className="agentGrid">{agents.map((a:any)=><button className={`agentCard ${selected===a.id?'selectedCard':''}`} key={a.id} onClick={()=>setSelected(a.id)}><div className="agentCardTop"><div className="bigAvatar">{a.name[0]}</div><div><b>{a.name}</b><span>{a.role}</span></div><i/></div><strong className={a.pnl>=0?'up':'down'}>{a.pnl>=0?'+':''}{money(a.pnl)}</strong><p>{a.action}</p><div className="skillBar"><i style={{width:`${a.skill}%`}}/></div><small>SKILL {a.skill} · RISK {a.risk.toFixed(1)}% · {a.wins}/{a.trades} WINS</small></button>)}</div></>}
function Portfolio({agents,markets,totalPnl,aum}:any){return <><Header eyebrow="PORTFOLIO" title="Capital allocation." sub="The portfolio is a consequence of autonomous decisions, not manual allocation."/><div className="summaryCards"><div className="heroCard"><small>AUM</small><h2>{short(aum)}</h2><span>paper capital</span></div><div className="card"><small>NET P&L</small><h2 className={totalPnl>=0?'up':'down'}>{totalPnl>=0?'+':''}{money(totalPnl)}</h2><span>all AI desks</span></div><div className="card"><small>POSITIONS</small><h2>{agents.reduce((s:any,a:any)=>s+(a.position>0?1:0),0)}</h2><span>open exposures</span></div></div><div className="card tableCard"><div className="cardHead"><span>DESK P&L</span><span>STRATEGY</span></div>{agents.map((a:any)=><div className="tableRow" key={a.id}><b>{a.name}</b><span>{a.strategy}</span><strong className={a.pnl>=0?'up':'down'}>{a.pnl>=0?'+':''}{money(a.pnl)}</strong></div>)}</div></>}
function Risk({agents}:any){const avg=agents.reduce((s:any,a:any)=>s+a.risk,0)/agents.length;return <><Header eyebrow="RISK ENGINE" title="The company protects itself." sub="Risk is a live agent layer. Exposure, concentration and desk limits are checked before execution."/><div className="riskGrid"><div className="heroCard"><small>PORTFOLIO RISK</small><h2>{avg.toFixed(1)}%</h2><span>weighted desk risk</span><div className="riskRing"><b>{avg<2?'LOW':'CONTROLLED'}</b></div></div><div className="card"><div className="cardHead"><span>RISK DESKS</span><ShieldCheck size={16}/></div>{agents.map((a:any)=><div className="riskRow" key={a.id}><b>{a.name}</b><div><i style={{width:`${Math.min(100,a.risk*18)}%`}}/></div><span>{a.risk.toFixed(1)}%</span></div>)}</div></div></>}
function Research({agents,markets}:any){return <><Header eyebrow="RESEARCH LAB" title="Agents learn from the market." sub="Signals, experiments and outcomes feed strategy memory. This layer will later connect to real model providers."/><div className="researchGrid"><div className="card researchMain"><div className="cardHead"><span>ACTIVE EXPERIMENTS</span><BrainCircuit size={16}/></div>{agents.slice(0,8).map((a:any)=><div className="experiment" key={a.id}><div className="bigAvatar">{a.name[0]}</div><div><b>{a.strategy}</b><span>{a.name} · testing against {a.symbol}</span></div><strong>{a.skill}/100</strong></div>)}</div><div className="card"><div className="cardHead"><span>MARKET SIGNALS</span><LineChart size={16}/></div>{markets.map((m:any)=><div className="signal" key={m.symbol}><b>{m.symbol}</b><span>{m.change>1?'BUY BIAS':m.change<-.8?'SELL BIAS':'NEUTRAL'}</span><strong className={m.change>=0?'up':'down'}>{m.change.toFixed(2)}%</strong></div>)}</div></div></>}

createRoot(document.getElementById('root')!).render(<App/>);
