import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, BarChart3, BrainCircuit, Building2, ChevronRight, CircleDollarSign, Cpu, Gauge, LineChart, Radio, ShieldCheck, TrendingDown, TrendingUp, Users, Wallet, Zap } from 'lucide-react';
import './styles.css';

type Status='researching'|'deciding'|'trading'|'protecting'|'executing'|'monitoring';
type Agent={id:number;name:string;role:string;strategy:string;capital:number;cash:number;pnl:number;risk:number;status:Status;action:string;skill:number;trades:number;wins:number;position:number;avg:number;symbol:string;memory:string};
type Market={symbol:string;price:number;change:number;history:number[];volume:number};
type Page='command'|'markets'|'floor'|'workforce'|'portfolio'|'risk'|'research'|'board'|'system';
const symbols=['NVDA','MSFT','AAPL','BTC','SPX'];
const seedMarkets:Market[]=[
 {symbol:'NVDA',price:142.31,change:1.82,history:[136,137,138,137,139,141,140,142,141,143,142,142],volume:82},
 {symbol:'MSFT',price:505.74,change:.64,history:[499,501,500,502,504,503,505,504,506,505,505,506],volume:61},
 {symbol:'AAPL',price:245.18,change:-.38,history:[249,248,247,248,246,247,245,246,244,245,246,245],volume:54},
 {symbol:'BTC',price:113420,change:2.41,history:[109,110,111,110,112,111,113,112,114,113,114,113],volume:91},
 {symbol:'SPX',price:6512.8,change:.27,history:[6460,6480,6470,6490,6500,6490,6510,6500,6520,6510,6515,6513],volume:73}
];
const seedAgents:Agent[]=[
 {id:1,name:'ARIA',role:'CEO / Orchestrator',strategy:'Capital Allocation',capital:420000,cash:420000,pnl:12840,risk:1.4,status:'deciding',action:'Allocating capital between desks',skill:88,trades:21,wins:16,position:0,avg:0,symbol:'NVDA',memory:'Protect capital first. Scale only after evidence.'},
 {id:2,name:'NOVA',role:'Quant Research',strategy:'Statistical Momentum',capital:310000,cash:310000,pnl:9340,risk:2.1,status:'researching',action:'Scanning momentum anomalies',skill:91,trades:34,wins:23,position:0,avg:0,symbol:'MSFT',memory:'Momentum works best when volume confirms the move.'},
 {id:3,name:'ATLAS',role:'Trader',strategy:'Trend Following',capital:285000,cash:285000,pnl:14620,risk:2.8,status:'trading',action:'Managing NVDA trend position',skill:86,trades:48,wins:31,position:120,avg:140.8,symbol:'NVDA',memory:'Enter with trend confirmation; reduce after reversal.'},
 {id:4,name:'VEGA',role:'Macro Analyst',strategy:'News + Macro',capital:260000,cash:260000,pnl:-3820,risk:1.8,status:'monitoring',action:'Monitoring rates and macro regime',skill:83,trades:18,wins:9,position:0,avg:0,symbol:'SPX',memory:'Rates are changing the probability distribution of risk.'},
 {id:5,name:'SENTINEL',role:'Risk Manager',strategy:'Dynamic Risk Limits',capital:390000,cash:390000,pnl:5120,risk:.9,status:'protecting',action:'Validating exposure limits',skill:95,trades:7,wins:6,position:0,avg:0,symbol:'AAPL',memory:'No single thesis is allowed to threaten the company.'},
 {id:6,name:'ORBIT',role:'Execution',strategy:'Smart Execution',capital:335000,cash:335000,pnl:7880,risk:1.7,status:'executing',action:'Routing simulated order',skill:89,trades:39,wins:27,position:0,avg:0,symbol:'BTC',memory:'Execution quality matters as much as direction.'}
];
const money=(n:number)=>`€${Math.round(n).toLocaleString('en-US')}`;
function App(){
 const [page,setPage]=useState<Page>('command'); const [agents,setAgents]=useState(seedAgents); const [markets,setMarkets]=useState(seedMarkets); const [selected,setSelected]=useState(3); const [selectedSymbol,setSelectedSymbol]=useState('NVDA'); const [events,setEvents]=useState<string[]>(['SENTINEL approved ATLAS order','ORBIT routed NVDA BUY 120','NOVA detected momentum anomaly','VEGA updated macro risk score']); const [clock,setClock]=useState(0);
 useEffect(()=>{const timer=setInterval(()=>{setClock(c=>c+1);setMarkets(ms=>ms.map(m=>{const move=(Math.random()-.47)*(m.symbol==='BTC'?260:m.symbol==='SPX'?8:.95);const price=Math.max(.01,m.price+move);return {...m,price,change:m.change+(Math.random()-.48)*.18,history:[...m.history.slice(-15),m.symbol==='BTC'?price/1000:price],volume:Math.max(20,m.volume+(Math.random()-.5)*8)}}));},1200);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!clock)return;setAgents(as=>as.map(a=>{const market=markets.find(m=>m.symbol===a.symbol);if(!market)return a;const signal=market.change>1.1?1:market.change<-.9?-1:0;let position=a.position,cash=a.cash,pnl=a.pnl,trades=a.trades,wins=a.wins,action=a.action,status=a.status;
   if(a.id===3||a.id===2||a.id===6){if(signal>0&&position<150){const qty=a.id===3?10:5;const cost=qty*market.price;if(cash>cost){position+=qty;cash-=cost;trades++;status='trading';action=`Bought ${qty} ${a.symbol} after signal`;events.unshift(`${a.name} opened ${a.symbol} BUY ${qty}`)}}else if(signal<0&&position>0){const qty=Math.min(position,a.id===3?10:5);cash+=qty*market.price;position-=qty;trades++;wins+=market.price>a.avg?1:0;status='executing';action=`Reduced ${qty} ${a.symbol} on weakness`;events.unshift(`${a.name} reduced ${a.symbol} by ${qty}`)}else{status=a.id===2?'researching':a.id===6?'executing':'monitoring';action=signal>0?'Confirming bullish signal':'Waiting for stronger signal'}}
   const unreal=position*(market.price-a.avg);pnl+=unreal*0.018+(Math.random()-.47)*32;return {...a,cash,pnl,status,action,position,trades,wins,risk:Math.max(.5,Math.min(4.5,a.risk+(signal>0?.02:-.01)))}}));setEvents(e=>e.slice(0,9));},[clock]);
 const a=agents.find(x=>x.id===selected)!; const totalPnl=agents.reduce((s,x)=>s+x.pnl,0); const aum=agents.reduce((s,x)=>s+x.capital,0)+totalPnl; const m=markets.find(x=>x.symbol===selectedSymbol)!; const nav=[['command','Command Center'],['markets','Markets'],['floor','Trading Floor'],['workforce','AI Workforce'],['portfolio','Portfolio'],['risk','Risk'],['research','Research'],['board','Board Room'],['system','System']] as [Page,string][];
 const go=(p:Page)=>setPage(p);
 return <div className="app"><header><div className="brand"><div className="mark">D7</div><div><strong>DESTINY7 CAPITAL</strong><span>Autonomous Financial Company</span></div></div><div className="live"><i/> AUTONOMOUS SIMULATION</div><div className="topstats"><div><span>SIMULATED AUM</span><b>{money(aum)}</b></div><div><span>NET P&L</span><b className={totalPnl>=0?'up':'down'}>{totalPnl>=0?'+':''}{money(totalPnl)}</b></div><div><span>AI AGENTS</span><b>{agents.length}</b></div></div></header>
 <div className="layout"><nav><div className="navlabel">COMPANY</div>{nav.map(([id,label])=><button key={id} className={page===id?'navactive':''} onClick={()=>go(id)}>{icon(id)}<span>{label}</span><ChevronRight size={12}/></button>)}<div className="navbox"><Zap size={15}/><div><b>SELF-RUNNING</b><small>Agents decide, trade, learn and adapt automatically.</small></div></div></nav>
 <main><div className="crumb"><span>DESTINY7 CAPITAL</span><b>/</b><strong>{nav.find(x=>x[0]===page)?.[1]}</strong><em>LOCAL PAPER SIMULATION</em></div>{page==='command'&&<Command agents={agents} markets={markets} events={events} aum={aum} pnl={totalPnl} go={go} select={setSelected}/>} {page==='markets'&&<Markets markets={markets} selected={selectedSymbol} setSelected={setSelectedSymbol} agents={agents}/>} {page==='floor'&&<Floor agents={agents} selected={selected} setSelected={setSelected} go={go}/>} {page==='workforce'&&<Workforce agents={agents} selected={selected} setSelected={setSelected}/>} {page==='portfolio'&&<Portfolio agents={agents} markets={markets} aum={aum} pnl={totalPnl}/>} {page==='risk'&&<Risk agents={agents}/>} {page==='research'&&<Research agents={agents} markets={markets}/>} {page==='board'&&<Board agents={agents} pnl={totalPnl}/>} {page==='system'&&<System clock={clock}/>}</main>
 <aside className="inspector"><div className="panelHead"><div><small>ACTIVE AI EMPLOYEE</small><h2>{a.name}</h2></div><div className="avatar">{a.name[0]}</div></div><div className="role">{a.role}<span>RUNNING</span></div><div className="metrics"><div><span>CAPITAL</span><b>{money(a.capital)}</b></div><div><span>P&L</span><b className={a.pnl>=0?'up':'down'}>{a.pnl>=0?'+':''}{money(a.pnl)}</b></div><div><span>RISK</span><b>{a.risk.toFixed(1)}%</b></div><div><span>WIN RATE</span><b>{Math.round(a.wins/Math.max(1,a.trades)*100)}%</b></div></div><div className="decision"><small>WHAT IT IS DOING NOW</small><strong>{a.action}</strong><div><Gauge size={15}/>Skill <b>{a.skill}/100</b></div><div><Wallet size={15}/>Position <b>{a.position} {a.symbol}</b></div></div><div className="memory"><small>AGENT MEMORY</small><p>{a.memory}</p></div><div className="listTitle">WORKFORCE <span>{agents.length}/50</span></div>{agents.map(x=><button className={`agentrow ${x.id===selected?'active':''}`} onClick={()=>setSelected(x.id)} key={x.id}><div className="miniAvatar">{x.name[0]}</div><div><b>{x.name}</b><small>{x.status} · {money(x.pnl)}</small></div><ChevronRight size={13}/></button>)}</aside></div>
 <footer><span><Cpu size={13}/> AI DECISION CORE ONLINE</span><span><ShieldCheck size={13}/> RISK ENGINE ONLINE</span><span><CircleDollarSign size={13}/> PAPER CAPITAL €2.00M</span><span><Activity size={13}/> MARKET ENGINE RUNNING</span><span>v0.2 AUTONOMOUS SIMULATION</span></footer></div>;
}
function icon(id:string){const p=14;if(id==='command')return <Gauge size={p}/>;if(id==='markets')return <LineChart size={p}/>;if(id==='floor')return <Building2 size={p}/>;if(id==='workforce')return <Users size={p}/>;if(id==='portfolio')return <Wallet size={p}/>;if(id==='risk')return <ShieldCheck size={p}/>;if(id==='research')return <BrainCircuit size={p}/>;if(id==='board')return <Users size={p}/>;return <Cpu size={p}/>}
function Header({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div className="viewhead"><div><small>{eyebrow}</small><h1>{title}</h1><p>{sub}</p></div><div className="livebox"><i/> LIVE<br/><b>AUTONOMOUS</b></div></div>}
function Command({agents,markets,events,aum,pnl,go,select}:any){return <><Header eyebrow="COMMAND CENTER" title="The company runs itself." sub="Agents continuously observe markets, make decisions, execute paper trades, manage risk and learn from outcomes."/><div className="how"><div className="howstep"><b>01</b><strong>OBSERVE</strong><span>Market engine feeds prices, volume and signals.</span></div><div className="howstep"><b>02</b><strong>DECIDE</strong><span>Each agent applies its own strategy and memory.</span></div><div className="howstep"><b>03</b><strong>ACT</strong><span>Risk checks and execution happen automatically.</span></div><div className="howstep"><b>04</b><strong>LEARN</strong><span>Results update P&L, skill and future decisions.</span></div></div><div className="dashgrid"><div className="heroCard"><div className="cardhead"><span>COMPANY PERFORMANCE</span><b>RUNNING WITHOUT MANUAL INPUT</b></div><div className="bigmoney">{money(aum)}</div><div className="muted">simulated assets under management</div><div className="profit"><TrendingUp size={16}/><strong>{pnl>=0?'+':''}{money(pnl)}</strong><span>cumulative simulated P&L</span></div><div className="bars">{[32,48,42,61,55,73,67,82,76,94,88,100].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="card"><div className="cardhead"><span>LIVE DECISIONS</span><b>{agents.filter((a:any)=>a.status==='trading'||a.status==='executing').length} ACTIVE</b></div>{agents.slice(0,5).map((x:any)=><button className="decisionrow" key={x.id} onClick={()=>select(x.id)}><div className="dot"/><div><b>{x.name}</b><span>{x.action}</span></div><strong className={x.pnl>=0?'up':'down'}>{x.pnl>=0?'+':''}{money(x.pnl)}</strong></button>)}</div><div className="card"><div className="cardhead"><span>MARKET PULSE</span><button onClick={()=>go('markets')}>OPEN MARKETS →</button></div>{markets.map((x:any)=><div className="marketrow" key={x.symbol}><b>{x.symbol}</b><span>{x.price.toLocaleString(undefined,{maximumFractionDigits:2})}</span><strong className={x.change>=0?'up':'down'}>{x.change>=0?'+':''}{x.change.toFixed(2)}%</strong></div>)}</div><div className="card"><div className="cardhead"><span>EVENT STREAM</span><Radio size={15}/></div>{events.slice(0,7).map((e:string,i:number)=><div className="event" key={i}><i/>{e}</div>)}</div></div></>}
function Markets({markets,selected,setSelected,agents}:any){const m=markets.find((x:any)=>x.symbol===selected)!;const owners=agents.filter((a:any)=>a.symbol===selected);return <><Header eyebrow="MARKETS" title="Where agents find opportunities." sub="This is the market engine. Prices move automatically and agents react to the same information."/><div className="marketlayout"><div className="card marketlist">{markets.map((x:any)=><button className={x.symbol===selected?'symbolactive':''} onClick={()=>setSelected(x.symbol)} key={x.symbol}><b>{x.symbol}</b><span>{x.price.toLocaleString(undefined,{maximumFractionDigits:2})}</span><strong className={x.change>=0?'up':'down'}>{x.change>=0?'+':''}{x.change.toFixed(2)}%</strong></button>)}</div><div className="card chartcard"><div className="cardhead"><span>{m.symbol} · SIMULATED PRICE</span><b className={m.change>=0?'up':'down'}>{m.change>=0?'+':''}{m.change.toFixed(2)}%</b></div><div className="price">{m.price.toLocaleString(undefined,{maximumFractionDigits:2})}</div><div className="chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={m.history.map((v:number,i:number)=>`${i*(700/(m.history.length-1))},${210-(v/Math.max(...m.history)*180)}`).join(' ')}/></svg></div><div className="chartmeta"><span>VOLUME {m.volume.toFixed(0)}%</span><span>MARKET ENGINE LIVE</span></div></div><div className="card"><div className="cardhead"><span>AGENTS WATCHING {m.symbol}</span></div>{owners.length?owners.map((x:any)=><div className="researchrow" key={x.id}><div className="miniAvatar">{x.name[0]}</div><div><b>{x.name}</b><span>{x.role}</span></div><strong>{x.action}</strong></div>):<p className="empty">No dedicated agent position. Agents are free to discover it.</p>}</div></div></>}
function Floor({agents,selected,setSelected,go}:any){return <><Header eyebrow="TRADING FLOOR" title="See the company working." sub="Every desk is an agent. Click a desk to inspect its live state."/><div className="floor"><div className="wallScreen"><small>DESTINY7 MARKET MATRIX</small><b>DECISIONS / EXPOSURE / RISK</b><div className="screenChart">{[28,45,36,59,50,67,61,82,74,92,86,100].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div><div className="screenNumbers"><span>RISK <b>1.7%</b></span><span>ORDERS <b>LIVE</b></span></div></div>{agents.map((agent:any,i:number)=><button className={`desk ${agent.id===selected?'selected':''}`} key={agent.id} style={{left:`${12+(i%3)*26}%`,top:`${31+Math.floor(i/3)*31}%`}} onClick={()=>setSelected(agent.id)}><div className="monitor"><i/><span>{agent.action}</span><em>{agent.role}</em></div><div className="deskSurface"><div className="chair"/><div className="agent"><strong>{agent.name}</strong><small>{agent.status.toUpperCase()}</small></div></div></button>)}<button className="meeting" onClick={()=>go('board')}><Users size={18}/><span>BOARD ROOM</span><small>Strategy + allocation</small></button><div className="ceo"><Building2 size={18}/><span>CEO OFFICE</span></div></div></>}
function Workforce({agents,selected,setSelected}:any){return <><Header eyebrow="AI WORKFORCE" title="Autonomous employees." sub="They have roles, strategies, memory, capital, risk limits and performance. They do not wait for a human click."/><div className="table card"><div className="tr th"><span>AGENT</span><span>ROLE</span><span>STATE</span><span>CAPITAL</span><span>P&L</span><span>WIN RATE</span></div>{agents.map((x:any)=><button className={`tr ${x.id===selected?'rowactive':''}`} key={x.id} onClick={()=>setSelected(x.id)}><span><b>{x.name}</b><small>skill {x.skill}/100</small></span><span>{x.role}</span><span><i className="state"/> {x.status}</span><span>{money(x.capital)}</span><span className={x.pnl>=0?'up':'down'}>{x.pnl>=0?'+':''}{money(x.pnl)}</span><span>{Math.round(x.wins/Math.max(1,x.trades)*100)}%</span></button>)}</div></>}
function Portfolio({agents,markets,aum,pnl}:any){return <><Header eyebrow="PORTFOLIO" title="Capital follows decisions." sub="Positions, cash and performance are consequences of what the agents actually decide in the simulation."/><div className="statsgrid"><Stat label="SIMULATED AUM" value={money(aum)}/><Stat label="NET P&L" value={`${pnl>=0?'+':''}${money(pnl)}`} cls={pnl>=0?'up':'down'}/><Stat label="OPEN POSITIONS" value={String(agents.filter((a:any)=>a.position>0).length)}/><Stat label="TOTAL TRADES" value={String(agents.reduce((s:number,a:any)=>s+a.trades,0))}/></div><div className="card table"><div className="tr th"><span>AGENT</span><span>ASSET</span><span>POSITION</span><span>AVG PRICE</span><span>CASH</span><span>P&L</span></div>{agents.map((x:any)=><div className="tr" key={x.id}><span><b>{x.name}</b><small>{x.strategy}</small></span><span>{x.symbol}</span><span>{x.position}</span><span>{x.avg?x.avg.toFixed(2):'—'}</span><span>{money(x.cash)}</span><span className={x.pnl>=0?'up':'down'}>{x.pnl>=0?'+':''}{money(x.pnl)}</span></div>)}</div></>}
function Risk({agents}:any){const avg=agents.reduce((s:number,a:any)=>s+a.risk,0)/agents.length;return <><Header eyebrow="RISK" title="No agent controls the company alone." sub="Sentinel continuously evaluates exposure and can constrain the trading agents when risk rises."/><div className="riskgrid"><div className="riskdial"><small>COMPANY RISK</small><strong>{avg.toFixed(1)}%</strong><span>within simulated limits</span></div><div className="card"><div className="cardhead"><span>RISK CONTROLS</span><ShieldCheck size={16}/></div>{[['Max single position','15%'],['Max desk risk','4.5%'],['Daily loss stop','2.0%'],['Emergency protection','ACTIVE']].map(x=><div className="limit" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div><div className="card"><div className="cardhead"><span>RISK BY AGENT</span></div>{agents.map((x:any)=><div className="riskbar" key={x.id}><b>{x.name}</b><div><i style={{width:`${Math.min(100,x.risk*20)}%`}}/></div><span>{x.risk.toFixed(1)}%</span></div>)}</div></>}
function Research({agents,markets}:any){return <><Header eyebrow="RESEARCH" title="Agents form hypotheses, not certainties." sub="Research is continuously generated from the simulated market state and passed to traders and risk."/><div className="researchgrid">{agents.filter((a:any)=>a.role.includes('Research')||a.role.includes('Macro')||a.role.includes('CEO')).map((x:any)=><div className="card researchcard" key={x.id}><div className="cardhead"><span>{x.name} · {x.role}</span><BrainCircuit size={16}/></div><h3>{x.strategy}</h3><p>{x.action}. Confidence changes with market evidence; the agent can reverse its view.</p><div className="hyp"><span>MEMORY</span><b>{x.memory}</b></div><div className="signals">{markets.slice(0,3).map((m:any)=><span key={m.symbol} className={m.change>=0?'up':'down'}>{m.symbol} {m.change>=0?'+':''}{m.change.toFixed(2)}%</span>)}</div></div>)}</div></>}
function Board({agents,pnl}:any){return <><Header eyebrow="BOARD ROOM" title="Strategic decisions." sub="The board is an autonomous coordination layer. It allocates attention and capital based on company performance and risk."/><div className="board"><div className="boardtable"><div className="boardcenter"><Building2 size={26}/><b>DESTINY7 BOARD</b><span>Next automatic review in 00:42</span></div>{agents.map((x:any)=><div className="boardseat" key={x.id}><div className="miniAvatar">{x.name[0]}</div><b>{x.name}</b><small>{x.role}</small></div>)}</div><div className="card agenda"><div className="cardhead"><span>AUTOMATIC AGENDA</span><b>ACTIVE</b></div><div>01 · Review {pnl>=0?'profit growth':'drawdown'} and capital efficiency</div><div>02 · Evaluate strategy changes</div><div>03 · Check risk limits</div><div>04 · Approve next allocation cycle</div></div></div></>}
function System({clock}:any){return <><Header eyebrow="SYSTEM" title="The machinery underneath." sub="This page makes the simulation boundary explicit. Everything here is local and paper-only."/><div className="systemgrid">{[['AI Decision Core','ONLINE','Generates autonomous decisions'],['Market Engine','RUNNING','Moves simulated prices'],['Risk Engine','ONLINE','Checks every proposed action'],['Memory Layer','ONLINE','Stores agent learning state'],['Execution Engine','RUNNING','Fills paper orders'],['Persistence','LOCAL','No external money or broker connected']].map(x=><div className="card sys" key={x[0]}><div className="sysicon"><Cpu size={18}/></div><div><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div></div>)}</div><div className="card systemclock"><span>SIMULATION TICKS</span><b>{clock.toLocaleString()}</b><small>The clock never stops while this page is open.</small></div></>}
function Stat({label,value,cls}:{label:string;value:string;cls?:string}){return <div className="stat card"><span>{label}</span><b className={cls}>{value}</b></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
